/-
Copyright 2026 Burc Gokden. Released under the Apache 2.0 license.

# The density operator D = Qᵀ Q

The deductive path of PLGA starts from the density operator
`D = Q̃ᵀ Q̃` of the (rotary-rotated) queries.  This file proves the
algebraic content of Proposition 3.6 of the paper:

* `density_isSymm`           : `Qᵀ Q` is symmetric;
* `density_posSemidef`       : `Qᵀ Q` is positive semidefinite;
* `density_quadratic_nonneg` : the quadratic form `vᵀ (Qᵀ Q) v` is the
  squared norm of `Q v`, hence nonnegative;
* `density_rank`, `density_rank_le` : `rank (Qᵀ Q) = rank Q <= min S dk`,
  so for short contexts (`S < dk`) the instance geometry seen by the
  metric learner is necessarily rank-deficient.
-/
import Mathlib

namespace PldrLlm

open Matrix

variable {S dk : ℕ}

/-- The density operator `Qᵀ Q` is symmetric. -/
theorem density_isSymm (Q : Matrix (Fin S) (Fin dk) ℝ) :
    (Qᵀ * Q).IsSymm := by
  rw [Matrix.IsSymm, Matrix.transpose_mul, Matrix.transpose_transpose]

/-- The density operator is positive semidefinite. -/
theorem density_posSemidef (Q : Matrix (Fin S) (Fin dk) ℝ) :
    (Qᵀ * Q).PosSemidef := by
  simpa using Matrix.posSemidef_conjTranspose_mul_self Q

/-- The quadratic form of the density operator is the squared Euclidean
norm of `Q v`: explicitly, `v ⬝ (QᵀQ) v = (Q v) ⬝ (Q v) >= 0`. -/
theorem density_quadratic_nonneg (Q : Matrix (Fin S) (Fin dk) ℝ)
    (v : Fin dk → ℝ) :
    0 ≤ v ⬝ᵥ ((Qᵀ * Q) *ᵥ v) := by
  rw [← Matrix.mulVec_mulVec, Matrix.dotProduct_mulVec,
    Matrix.vecMul_transpose]
  simp only [dotProduct]
  exact Finset.sum_nonneg fun i _ => mul_self_nonneg _

/-- `rank (Qᵀ Q) = rank Q`: no information is lost or created by forming
the Gram matrix. -/
theorem density_rank (Q : Matrix (Fin S) (Fin dk) ℝ) :
    (Qᵀ * Q).rank = Q.rank :=
  Matrix.rank_transpose_mul_self Q

/-- `rank (Qᵀ Q) <= min S dk`: for short contexts the density operator is
rank-deficient, so strictly positive-definite structure in the metric
tensor must be generated by the learner, not present in one instance. -/
theorem density_rank_le (Q : Matrix (Fin S) (Fin dk) ℝ) :
    (Qᵀ * Q).rank ≤ min S dk := by
  rw [density_rank]
  refine le_min ?_ ?_
  · simpa using Q.rank_le_card_height
  · simpa using Q.rank_le_card_width

end PldrLlm
